# Generated by Django 3.2.4 on 2021-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0003_content_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainadmin',
            fields=[
                ('a_username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('a_password', models.CharField(max_length=15)),
            ],
        ),
    ]
