# Generated by Django 2.2.7 on 2021-09-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0004_mainadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mainadmin',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='userLimit',
            field=models.IntegerField(default=0),
        ),
    ]
