# Generated by Django 3.2 on 2022-03-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPS', '0005_auto_20210901_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='uniqueCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
